language: java

rvm:
  - 2.2.5

sudo: required
services: 
  - docker

env:
  matrix:
  - INSTANCE: share-ubuntu-1404

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: 
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - xmllint --version

install:
  # setup ci for test formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - git clone https://github.com/saltstack-formulas/tomcat-formula.git /tmp/tomcat
  - wget http://repo1.maven.org/maven2/com/h2database/h2/1.4.190/h2-1.4.190.jar -O /opt/h2-1.4.190.jar
  - java -cp /opt/h2-1.4.190.jar org.h2.tools.Server -web -webPort 8081 -webAllowOthers -tcp -tcpPort 8082 -tcpAllowOthers -baseDir /opt/db &
  - bundle install

addons:
  apt:
    packages:
    - libxml2-utils

script: bundle exec kitchen verify ${INSTANCE}
