require_relative '../../../kitchen/data/spec_helper'

describe 'alfresco/share.sls' do
   when 'ubuntu'
      pkgs_installed = %w(libtcnative-1)
      global_properties = '/var/lib/tomcat7/shared/classes/alfresco-global.properties'
      custom_share_config = '/var/lib/tomcat7/shared/classes/alfresco-global.properties'
      catalina_logfile = '/var/log/tomcat7/catalina.out'
      service = 'tomcat7'
      user = 'tomcat7'
      group = 'tomcat7'
  end

  describe file(global_properties) do
    it { should be_file }
    its(:content) { should contain('This file is managed/autogenerated by salt.') }
  end

  # describe file(custom_share_config) do
  #   it { should be_file }
  #   its(:content) { should contain('This file is managed/autogenerated by salt.') }

  #   describe command("xmllint --noout #{server_config}") do
  #     its(:exit_status) { should eq 0 }
  #   end
  # end  

  describe file(catalina_logfile) do
    it { should be_file }
    its(:content) { should contain('INFO: Server startup in') }
  end
end